name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때마다 배포

jobs:
  build:
    runs-on: windows-latest  # Windows 환경에서 실행

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 원하는 Python 버전

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Streamlit app
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
        run: |
          streamlit run app.py --server.enableCORS false --server.enableXsrfProtection false
